// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnkifmuhkhdjbswraini.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indua2lmbXVoa2hkamJzd3JhaW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODQzMzYsImV4cCI6MjA3MTc2MDMzNn0.YIBOmZmkDjErl1FChGHZ8Rqd14G41h-a7PrVuMRUZe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});